"""Assemble reference/references.bib from verified citation metadata.

Each entry is resolved live through the same APIs as ``verify_citation`` —
Crossref for DOIs, DataCite for arXiv ids — so every BibTeX record in the
reference pack comes from a resolvable identifier rather than a re-typed
bibliography. The manifest below pins one canonical identifier per paper
(preferring the published version of record where one exists) and a stable
citation key; ``slug`` is the on-disk filename stem so the per-paper transcript
headers and this file stay in lock-step.

Usage:
    python tools/build_references.py --out reference/references.bib
"""

from __future__ import annotations

import argparse
import sys
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import verify_citation as vc  # noqa: E402

# (key, slug, kind, identifier) -- kind is "doi" or "arxiv".
# "arxiv" entries auto-upgrade to the published DOI when DataCite records one.
MANIFEST = [
    ("jelincic2025", "jelincic-2025-probabilistic-hardware-architecture", "arxiv", "2510.23972"),
    ("ayodele2022", "ayodele-2022-penalty-weights-permutation", "doi", "10.1007/978-3-031-04148-8_11"),
    ("mucke2025", "mucke-2025-qubolite", "arxiv", "2509.21321"),
    ("zaman2021", "zaman-2021-pyqubo", "arxiv", "2103.01708"),
    ("pawlowski2026", "pawlowski-2026-simulated-bifurcation-annealing", "arxiv", "2604.01050"),
    ("tao2026", "tao-2026-tabu-simulated-bifurcation", "doi", "10.1038/s42005-026-02538-2"),
    ("turingq2025", "turingq-2025-qis3-qubo-solver", "arxiv", "2506.04596"),
    ("alessandroni2025bigm", "alessandroni-2025-quantum-big-m", "doi", "10.1038/s41534-025-01067-0"),
    ("alessandroni2026weights", "alessandroni-2026-penalization-weights", "arxiv", "2604.02416"),
    ("doucet2026", "doucet-2026-qubo-encoding-thermodynamics", "arxiv", "2601.04402"),
    ("vehtari2021", "vehtari-2021-rhat-ess", "doi", "10.1214/20-BA1221"),
    ("camsari2017invertible", "camsari-2016-stochastic-pbits-invertible-logic", "arxiv", "1610.00377"),
    ("camsari2019pbits", "camsari-2018-probabilistic-spin-logic", "doi", "10.1063/1.5055860"),
    ("duffee2025pdits", "camsari-2025-pdits-extended-variable", "arxiv", "2506.00269"),
    ("duffee2026qap", "duffee-2026-pdit-ising-qap", "arxiv", "2605.24408"),
    ("lucas2014", "lucas-2014-ising-formulations", "doi", "10.3389/fphy.2014.00005"),
    ("magar2025", "magar-2025-pc-cop-pbit-accelerator", "arxiv", "2504.04543"),
    ("onizawa2026", "onizawa-2026-parallel-pbit-ising", "arxiv", "2604.01564"),
    ("arshad2026", "arshad-2026-qubo-suspension-benchmark", "doi", "10.3390/machines14020248"),
    ("bernalneira2024", "bernal-neira-2024-quantum-heuristics-ising-machines", "arxiv", "2402.10255"),
    ("oshiyama2022", "oshiyama-2022-qubo-heuristic-benchmark", "doi", "10.1038/s41598-022-06070-5"),
    ("shaglel2025", "shaglel-2025-maxcut-ising-benchmark", "arxiv", "2507.22117"),
]

# Conference papers without a registered DOI: hand-built from the PDF front
# matter, verified against the paper itself rather than an API.
MANUAL = {
    "turner2018": {
        "slug": "turner-2018-sampler-diagnostics",
        "bibtex": (
            "@inproceedings{turner2018,\n"
            "  author = {Ryan Turner and Brady Neal},\n"
            "  title = {{How well does your sampler really work?}},\n"
            "  year = {2018},\n"
            "  booktitle = {Proceedings of the 34th Conference on Uncertainty in "
            "Artificial Intelligence (UAI)},\n"
            "  note = {arXiv:1712.06006},\n"
            "}"
        ),
    },
}


def build() -> str:
    blocks: list[str] = [
        "% Gibbsiq reference pack -- canonical citations.",
        "% Generated by tools/build_references.py; every entry resolved via",
        "% Crossref (DOI) or DataCite (arXiv). Do not hand-edit; re-run instead.",
        "",
    ]
    for key, slug, kind, ident in MANIFEST:
        record = vc.resolve_doi(ident) if kind == "doi" else vc.resolve_arxiv(ident)
        bibtex = vc.to_bibtex(record, key)
        blocks.append(f"% {slug}")
        blocks.append(bibtex)
        blocks.append("")
        time.sleep(1)  # stay polite to Crossref / DataCite
    for key, info in MANUAL.items():
        blocks.append(f"% {info['slug']}")
        blocks.append(info["bibtex"])
        blocks.append("")
    return "\n".join(blocks).rstrip() + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", type=Path, default=Path("reference/references.bib"))
    args = parser.parse_args(argv)
    text = build()
    args.out.write_text(text, encoding="utf-8")
    print(f"wrote {args.out} ({text.count('@')} entries)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
