"""Generate brute-force-verifiable ground-truth optimization fixtures.

Every instance produced here is small enough to solve by exhaustive
enumeration, so the optimum, the degeneracy, and a witness state are *proven*
rather than "best known". The output matches the golden-fixture schema used by
``src/gibbsiq/evaluation.py`` so a future Gibbsiq solver can be scored against
these instances with the existing JSON evaluator.

Conventions (do not violate; see reference/08-evaluation/equation-audit.md):
    Ising energy  E(s) = offset + sum_i h_i s_i + sum_{i<j} J_ij s_i s_j,
                  with s_i in {-1, +1} and upper-triangle quadratic terms only.
    Max-Cut       Ising energy = sum_edges s_u s_v; cut = (|E| - energy) / 2.

Provenance: instances are generated by a deterministic, explicitly-seeded PRNG
(`random.Random(seed)`), so the corpus is reproducible from the recorded seed.
A content checksum of the emitted document is printed for artifact tracking.

Usage (PowerShell):
    python tools/generate_ground_truth.py --out OUTPUT.json
"""

from __future__ import annotations

import argparse
import hashlib
import itertools
import json
import random
from pathlib import Path
from typing import Any, Iterable

SCHEMA_VERSION = "2026-05-31"
GENERATOR = "tools/generate_ground_truth.py"
ENERGY_CONVENTION = (
    "E(s) = offset + sum_i h_i s_i + sum_{i<j} J_ij s_i s_j, s_i in {-1,+1}"
)
# Cap on how many witness states we serialize per fixture. The full degeneracy
# COUNT is always exact; the witness list is a representative sample and is
# never used to assert completeness.
MAX_WITNESSES = 8

# Source citations for each formulation / closed-form optimum. Keys are stamped
# into every fixture's ``provenance.formulation_source`` so the corpus is
# traceable to primary literature in the final paper. Self-generated optima are
# proven by enumeration (the proof is the brute force), but the *encoding* of
# each family and the *closed-form* optima of named graphs are paper-backed.
CITATIONS = {
    "lucas2014": (
        "Lucas, A. (2014). Ising formulations of many NP problems. "
        "Frontiers in Physics 2:5. DOI 10.3389/fphy.2014.00005; arXiv:1302.5843."
    ),
    "sk1975": (
        "Sherrington, D. & Kirkpatrick, S. (1975). Solvable Model of a "
        "Spin-Glass. Phys. Rev. Lett. 35, 1792. DOI 10.1103/PhysRevLett.35.1792."
    ),
    "edwards1973": (
        "Edwards, C. S. (1973). Some extremal properties of bipartite "
        "subgraphs. Canadian J. of Mathematics 25(3):475-485. "
        "DOI 10.4153/CJM-1973-048-x."
    ),
    "west2001": (
        "West, D. B. (2001). Introduction to Graph Theory, 2nd ed. "
        "Prentice Hall (cycle max-cut, p. 76)."
    ),
    "diestel2017": (
        "Diestel, R. (2017). Graph Theory, 5th ed. Springer. "
        "DOI 10.1007/978-3-662-53622-3 (complete bipartite graphs)."
    ),
    "harary1969": (
        "Harary, F. (1969). Graph Theory. Addison-Wesley "
        "(hypercube bipartiteness, ch. 13)."
    ),
    "barahona1983": (
        "Barahona, F. (1983). The max-cut problem on graphs not contractible "
        "to K5. Operations Research Letters 2(3):107-111. "
        "DOI 10.1016/0167-6377(83)90016-0."
    ),
}


# --------------------------------------------------------------------------- #
# Enumeration helpers
# --------------------------------------------------------------------------- #
def spin_assignments(n: int) -> Iterable[tuple[int, ...]]:
    """Yield every length-n vector over {-1, +1}."""
    for bits in itertools.product((-1, 1), repeat=n):
        yield bits


def binary_assignments(n: int) -> Iterable[tuple[int, ...]]:
    """Yield every length-n vector over {0, 1}."""
    for bits in itertools.product((0, 1), repeat=n):
        yield bits


def round6(value: float) -> float:
    """Round to 6 decimals to keep JSON stable and well inside 1e-9 tolerance."""
    return round(value + 0.0, 6)


def _spin_witness(spins: tuple[int, ...], n: int) -> dict[str, int]:
    """Serialize a spin vector as a ``{variable_name: +-1}`` witness state."""
    return {str(i): spins[i] for i in range(n)}


# --------------------------------------------------------------------------- #
# Max-Cut (Erdos-Renyi), exact optimum by enumeration
# --------------------------------------------------------------------------- #
def erdos_renyi_edges(n: int, prob: float, rng: random.Random) -> list[tuple[int, int]]:
    edges = []
    for u in range(n):
        for v in range(u + 1, n):
            if rng.random() < prob:
                edges.append((u, v))
    return edges


def solve_maxcut(n: int, edges: list[tuple[int, int]]) -> dict[str, Any]:
    num_edges = len(edges)
    best_energy = None
    degeneracy = 0
    witnesses: list[dict[str, int]] = []
    for spins in spin_assignments(n):
        energy = sum(spins[u] * spins[v] for u, v in edges)
        if best_energy is None or energy < best_energy:
            best_energy = energy
            degeneracy = 1
            witnesses = [_spin_witness(spins, n)]
        elif energy == best_energy:
            degeneracy += 1
            if len(witnesses) < MAX_WITNESSES:
                witnesses.append(_spin_witness(spins, n))
    best_cut = (num_edges - best_energy) // 2
    return {
        "num_nodes": n,
        "num_edges": num_edges,
        "best_cut_value": best_cut,
        "best_ising_energy": float(best_energy),
        "ground_state_degeneracy": degeneracy,
        "witness_spin_samples": witnesses,
    }


def maxcut_fixture(fixture_id: str, n: int, prob: float, seed: int) -> dict[str, Any]:
    rng = random.Random(seed)
    edges = erdos_renyi_edges(n, prob, rng)
    solved = solve_maxcut(n, edges)
    return {
        "id": fixture_id,
        "family": "maxcut",
        "purpose": (
            f"Exact Max-Cut optimum on a seeded Erdos-Renyi graph "
            f"(n={n}, p={prob}) verified by full 2^{n} enumeration."
        ),
        "provenance": {
            "generator": GENERATOR,
            "method": "exhaustive_enumeration",
            "seed": seed,
            "model": "erdos_renyi",
            "p_edge": prob,
            "formulation_source": CITATIONS["lucas2014"],
        },
        "input": {
            "format": "maxcut",
            "variables": [str(i) for i in range(n)],
            "edges": [[str(u), str(v)] for u, v in edges],
            "ising_energy": "sum_edges s_u s_v",
        },
        "expected": solved,
    }


# --------------------------------------------------------------------------- #
# Number partitioning, exact optimum by enumeration (Lucas 2014, sec. 2.1)
# H = A (sum_i n_i s_i)^2 ; perfect partition <=> ground energy 0.
# --------------------------------------------------------------------------- #
def solve_number_partition(numbers: list[int]) -> dict[str, Any]:
    best_diff = None
    degeneracy = 0
    witnesses: list[dict[str, Any]] = []
    n = len(numbers)
    for spins in spin_assignments(n):
        signed = sum(numbers[i] * spins[i] for i in range(n))
        diff = abs(signed)
        if best_diff is None or diff < best_diff:
            best_diff = diff
            degeneracy = 1
            witnesses = [_partition_witness(numbers, spins)]
        elif diff == best_diff:
            degeneracy += 1
            if len(witnesses) < MAX_WITNESSES:
                witnesses.append(_partition_witness(numbers, spins))
    return {
        "min_subset_sum_difference": best_diff,
        "best_ising_energy": float(best_diff * best_diff),
        "ground_state_degeneracy": degeneracy,
        "is_perfect_partition": best_diff == 0,
        "witness_partitions": witnesses,
    }


def _partition_witness(numbers: list[int], spins: tuple[int, ...]) -> dict[str, Any]:
    set_a = [numbers[i] for i in range(len(numbers)) if spins[i] == 1]
    set_b = [numbers[i] for i in range(len(numbers)) if spins[i] == -1]
    return {"set_plus": set_a, "set_minus": set_b}


def number_partition_fixture(
    fixture_id: str, n: int, max_value: int, seed: int, force_frustrated: bool = False
) -> dict[str, Any]:
    rng = random.Random(seed)
    numbers = [rng.randint(1, max_value) for _ in range(n)]
    if force_frustrated and sum(numbers) % 2 == 0:
        # An odd total sum makes a perfect (zero-difference) partition impossible,
        # so the proven optimum is guaranteed nonzero and the instance is
        # "frustrated" -- useful for catching near-but-not-exact solvers.
        numbers[0] += 1
    solved = solve_number_partition(numbers)
    return {
        "id": fixture_id,
        "family": "number_partition",
        "purpose": (
            f"Exact minimum subset-sum difference for {n} seeded integers, "
            f"verified by full 2^{n} enumeration (Lucas 2014, sec. 2.1)."
        ),
        "provenance": {
            "generator": GENERATOR,
            "method": "exhaustive_enumeration",
            "seed": seed,
            "value_range": [1, max_value],
            "source_basis": ["reference/05-theory/papers/lucas-2014-ising-formulations.md"],
            "formulation_source": CITATIONS["lucas2014"],
        },
        "input": {
            "format": "number_partition",
            "numbers": numbers,
            "ising_energy": "A * (sum_i n_i s_i)^2 with A=1",
        },
        "expected": solved,
    }


# --------------------------------------------------------------------------- #
# 0/1 Knapsack, exact optimum by enumeration
# --------------------------------------------------------------------------- #
def solve_knapsack(
    weights: list[int], values: list[int], capacity: int
) -> dict[str, Any]:
    n = len(weights)
    best_value = 0
    best_weight = 0
    degeneracy = 1  # the empty set is always feasible with value 0
    witnesses: list[list[int]] = [[]]
    for bits in binary_assignments(n):
        if bits == tuple([0] * n):
            continue
        weight = sum(weights[i] * bits[i] for i in range(n))
        if weight > capacity:
            continue
        value = sum(values[i] * bits[i] for i in range(n))
        selection = [i for i in range(n) if bits[i] == 1]
        if value > best_value:
            best_value = value
            best_weight = weight
            degeneracy = 1
            witnesses = [selection]
        elif value == best_value:
            degeneracy += 1
            if len(witnesses) < MAX_WITNESSES:
                witnesses.append(selection)
    return {
        "max_value": best_value,
        "weight_at_optimum": best_weight,
        "capacity": capacity,
        "num_optimal_selections": degeneracy,
        "witness_selections": witnesses,
    }


def knapsack_fixture(
    fixture_id: str, n: int, max_weight: int, max_value: int, seed: int
) -> dict[str, Any]:
    rng = random.Random(seed)
    weights = [rng.randint(1, max_weight) for _ in range(n)]
    values = [rng.randint(1, max_value) for _ in range(n)]
    capacity = sum(weights) // 2
    solved = solve_knapsack(weights, values, capacity)
    return {
        "id": fixture_id,
        "family": "knapsack",
        "purpose": (
            f"Exact 0/1 knapsack optimum for {n} seeded items, verified by full "
            f"2^{n} enumeration (Lucas 2014, sec. 5.2)."
        ),
        "provenance": {
            "generator": GENERATOR,
            "method": "exhaustive_enumeration",
            "seed": seed,
            "capacity_rule": "floor(sum(weights)/2)",
            "source_basis": ["reference/05-theory/papers/lucas-2014-ising-formulations.md"],
            "formulation_source": CITATIONS["lucas2014"],
        },
        "input": {
            "format": "knapsack",
            "weights": weights,
            "values": values,
            "capacity": capacity,
        },
        "expected": solved,
    }


# --------------------------------------------------------------------------- #
# Symmetric TSP, exact optimal tour by permutation enumeration
# --------------------------------------------------------------------------- #
def solve_tsp(distance: list[list[int]]) -> dict[str, Any]:
    n = len(distance)
    best_length = None
    degeneracy = 0
    witnesses: list[list[int]] = []
    # Fix city 0 as the start; enumerate orders of the remaining cities. Each
    # undirected cyclic tour is counted once by requiring the second city index
    # to be smaller than the last (kills direction reversal double-count).
    for perm in itertools.permutations(range(1, n)):
        if n > 2 and perm[0] > perm[-1]:
            continue
        tour = (0,) + perm
        length = sum(distance[tour[i]][tour[(i + 1) % n]] for i in range(n))
        if best_length is None or length < best_length:
            best_length = length
            degeneracy = 1
            witnesses = [list(tour)]
        elif length == best_length:
            degeneracy += 1
            if len(witnesses) < MAX_WITNESSES:
                witnesses.append(list(tour))
    return {
        "num_cities": n,
        "optimal_tour_length": best_length,
        "num_optimal_tours": degeneracy,
        "witness_tours": witnesses,
    }


def tsp_fixture(fixture_id: str, n: int, grid: int, seed: int) -> dict[str, Any]:
    rng = random.Random(seed)
    coords = [(rng.randint(0, grid), rng.randint(0, grid)) for _ in range(n)]
    distance = [[0] * n for _ in range(n)]
    for i in range(n):
        for j in range(i + 1, n):
            dx = coords[i][0] - coords[j][0]
            dy = coords[i][1] - coords[j][1]
            # Integer rounded Euclidean (TSPLIB EUC_2D style) keeps comparisons exact.
            d = round((dx * dx + dy * dy) ** 0.5)
            distance[i][j] = d
            distance[j][i] = d
    solved = solve_tsp(distance)
    return {
        "id": fixture_id,
        "family": "tsp",
        "purpose": (
            f"Exact optimal symmetric TSP tour for {n} seeded cities, verified by "
            f"({n}-1)!/2 permutation enumeration (Lucas 2014, sec. 7.2)."
        ),
        "provenance": {
            "generator": GENERATOR,
            "method": "exhaustive_enumeration",
            "seed": seed,
            "distance_metric": "rounded_euclidean_2d",
            "grid": grid,
            "source_basis": ["reference/05-theory/papers/lucas-2014-ising-formulations.md"],
            "formulation_source": CITATIONS["lucas2014"],
        },
        "input": {
            "format": "tsp",
            "num_cities": n,
            "coordinates": [list(c) for c in coords],
            "distance_matrix": distance,
        },
        "expected": solved,
    }


# --------------------------------------------------------------------------- #
# Sherrington-Kirkpatrick spin glass, exact ground state by enumeration
# Fully connected, J_ij in {-1, +1}, h = 0.
# --------------------------------------------------------------------------- #
def solve_ising(
    n: int, couplings: dict[tuple[int, int], float], fields: dict[int, float]
) -> dict[str, Any]:
    best_energy = None
    degeneracy = 0
    witnesses: list[dict[str, int]] = []
    for spins in spin_assignments(n):
        energy = sum(fields.get(i, 0.0) * spins[i] for i in range(n))
        for (u, v), j in couplings.items():
            energy += j * spins[u] * spins[v]
        if best_energy is None or energy < best_energy - 1e-12:
            best_energy = energy
            degeneracy = 1
            witnesses = [_spin_witness(spins, n)]
        elif abs(energy - best_energy) <= 1e-12:
            degeneracy += 1
            if len(witnesses) < MAX_WITNESSES:
                witnesses.append(_spin_witness(spins, n))
    return {
        "num_spins": n,
        "ground_state_energy": round6(best_energy),
        "ground_state_degeneracy": degeneracy,
        "witness_spin_samples": witnesses,
    }


def sk_spin_glass_fixture(fixture_id: str, n: int, seed: int) -> dict[str, Any]:
    rng = random.Random(seed)
    couplings: dict[tuple[int, int], float] = {}
    quadratic: dict[str, float] = {}
    for u in range(n):
        for v in range(u + 1, n):
            j = rng.choice((-1.0, 1.0))
            couplings[(u, v)] = j
            quadratic[f"{u},{v}"] = j
    solved = solve_ising(n, couplings, {})
    return {
        "id": fixture_id,
        "family": "sk_spin_glass",
        "purpose": (
            f"Exact ground state of a seeded Sherrington-Kirkpatrick spin glass "
            f"(n={n}, J in +/-1, h=0), verified by full 2^{n} enumeration."
        ),
        "provenance": {
            "generator": GENERATOR,
            "method": "exhaustive_enumeration",
            "seed": seed,
            "coupling_distribution": "uniform_pm_1",
            "formulation_source": CITATIONS["sk1975"],
        },
        "input": {
            "format": "ising",
            "variables": [str(i) for i in range(n)],
            "linear": {str(i): 0.0 for i in range(n)},
            "quadratic": quadratic,
            "offset": 0.0,
        },
        "expected": solved,
    }


# --------------------------------------------------------------------------- #
# Structured / named graphs: closed-form Max-Cut optima with primary-source
# citations, ALSO cross-checked against brute-force enumeration. Unlike the
# Erdos-Renyi instances (whose only proof is our own enumeration), these have an
# optimum that is independently published, so the corpus carries paper-cited
# ground truth -- not just self-generated values.
# --------------------------------------------------------------------------- #
def _normalize_edges(edges: Iterable[tuple[int, int]]) -> list[tuple[int, int]]:
    """Order each edge (u < v) and drop duplicates, keeping a stable order."""
    seen: set[tuple[int, int]] = set()
    ordered: list[tuple[int, int]] = []
    for u, v in edges:
        edge = (min(u, v), max(u, v))
        if edge not in seen:
            seen.add(edge)
            ordered.append(edge)
    return ordered


def complete_graph_edges(n: int) -> list[tuple[int, int]]:
    return _normalize_edges((u, v) for u in range(n) for v in range(u + 1, n))


def cycle_graph_edges(n: int) -> list[tuple[int, int]]:
    return _normalize_edges((i, (i + 1) % n) for i in range(n))


def complete_bipartite_edges(m: int, n: int) -> list[tuple[int, int]]:
    # Left vertices 0..m-1, right vertices m..m+n-1.
    return _normalize_edges((u, m + w) for u in range(m) for w in range(n))


def hypercube_edges(d: int) -> list[tuple[int, int]]:
    # Vertices are d-bit integers; edges join strings at Hamming distance 1.
    return _normalize_edges(
        (u, u ^ (1 << b)) for u in range(2 ** d) for b in range(d)
    )


def petersen_edges() -> list[tuple[int, int]]:
    # Outer 5-cycle 0..4, inner pentagram 5..9 (step 2), spokes i--i+5.
    outer = [(i, (i + 1) % 5) for i in range(5)]
    spokes = [(i, i + 5) for i in range(5)]
    inner = [(5 + i, 5 + (i + 2) % 5) for i in range(5)]
    return _normalize_edges(outer + spokes + inner)


def structured_maxcut_fixture(
    fixture_id: str,
    n: int,
    edges: list[tuple[int, int]],
    closed_form: int,
    citation_key: str,
    graph_name: str,
    formula: str,
) -> dict[str, Any]:
    edges = _normalize_edges(edges)
    solved = solve_maxcut(n, edges)
    if solved["best_cut_value"] != closed_form:
        raise ValueError(
            f"{fixture_id}: brute-force max-cut {solved['best_cut_value']} != "
            f"closed-form {formula} = {closed_form} for {graph_name}"
        )
    return {
        "id": fixture_id,
        "family": "maxcut",
        "purpose": (
            f"Max-Cut on the {graph_name} graph (n={n}, |E|={len(edges)}). "
            f"Closed-form optimum {formula} = {closed_form}, independently "
            f"cross-checked by full 2^{n} enumeration."
        ),
        "provenance": {
            "generator": GENERATOR,
            "method": "closed_form_with_enumeration_crosscheck",
            "graph": graph_name,
            "closed_form": formula,
            "formulation_source": CITATIONS[citation_key],
        },
        "input": {
            "format": "maxcut",
            "variables": [str(i) for i in range(n)],
            "edges": [[str(u), str(v)] for u, v in edges],
            "ising_energy": "sum_edges s_u s_v",
        },
        "expected": solved,
    }


# --------------------------------------------------------------------------- #
# Corpus assembly
# --------------------------------------------------------------------------- #
def build_corpus() -> dict[str, Any]:
    fixtures: list[dict[str, Any]] = []

    # Max-Cut: a few densities and sizes, all brute-forceable.
    fixtures.append(maxcut_fixture("gt_maxcut_er_n8_p50_s1", n=8, prob=0.5, seed=1))
    fixtures.append(maxcut_fixture("gt_maxcut_er_n10_p40_s2", n=10, prob=0.4, seed=2))
    fixtures.append(maxcut_fixture("gt_maxcut_er_n12_p30_s3", n=12, prob=0.3, seed=3))
    fixtures.append(maxcut_fixture("gt_maxcut_er_n14_p50_s4", n=14, prob=0.5, seed=4))

    # Number partitioning: includes both perfect and frustrated instances.
    fixtures.append(number_partition_fixture("gt_partition_n10_v20_s5", n=10, max_value=20, seed=5))
    fixtures.append(number_partition_fixture("gt_partition_n12_v50_s6", n=12, max_value=50, seed=6))
    fixtures.append(number_partition_fixture("gt_partition_n14_v99_s7", n=14, max_value=99, seed=7))
    # Frustrated (proven nonzero optimum) -- discriminates exact from near solvers.
    fixtures.append(
        number_partition_fixture("gt_partition_frustrated_n11_v30_s16", n=11, max_value=30, seed=16, force_frustrated=True)
    )
    fixtures.append(
        number_partition_fixture("gt_partition_frustrated_n13_v7_s17", n=13, max_value=7, seed=17, force_frustrated=True)
    )

    # Knapsack.
    fixtures.append(knapsack_fixture("gt_knapsack_n10_s8", n=10, max_weight=15, max_value=20, seed=8))
    fixtures.append(knapsack_fixture("gt_knapsack_n14_s9", n=14, max_weight=25, max_value=40, seed=9))

    # TSP (small enough for permutation enumeration).
    fixtures.append(tsp_fixture("gt_tsp_n6_s10", n=6, grid=100, seed=10))
    fixtures.append(tsp_fixture("gt_tsp_n8_s11", n=8, grid=100, seed=11))
    fixtures.append(tsp_fixture("gt_tsp_n9_s12", n=9, grid=100, seed=12))

    # SK spin glass.
    fixtures.append(sk_spin_glass_fixture("gt_sk_n8_s13", n=8, seed=13))
    fixtures.append(sk_spin_glass_fixture("gt_sk_n10_s14", n=10, seed=14))
    fixtures.append(sk_spin_glass_fixture("gt_sk_n12_s15", n=12, seed=15))

    # Structured / named graphs: closed-form Max-Cut optima with primary-source
    # citations, each independently cross-checked against full enumeration.
    # Complete graphs K_n: max-cut = floor(n^2/4) (Edwards 1973).
    fixtures.append(structured_maxcut_fixture(
        "gt_maxcut_complete_k4", n=4, edges=complete_graph_edges(4),
        closed_form=4, citation_key="edwards1973",
        graph_name="complete K4", formula="floor(4^2/4)"))
    fixtures.append(structured_maxcut_fixture(
        "gt_maxcut_complete_k5", n=5, edges=complete_graph_edges(5),
        closed_form=6, citation_key="edwards1973",
        graph_name="complete K5", formula="floor(5^2/4)"))
    fixtures.append(structured_maxcut_fixture(
        "gt_maxcut_complete_k6", n=6, edges=complete_graph_edges(6),
        closed_form=9, citation_key="edwards1973",
        graph_name="complete K6", formula="floor(6^2/4)"))
    fixtures.append(structured_maxcut_fixture(
        "gt_maxcut_complete_k7", n=7, edges=complete_graph_edges(7),
        closed_form=12, citation_key="edwards1973",
        graph_name="complete K7", formula="floor(7^2/4)"))
    # Cycles C_n: max-cut = n (even) / n-1 (odd) (West 2001).
    fixtures.append(structured_maxcut_fixture(
        "gt_maxcut_cycle_c6", n=6, edges=cycle_graph_edges(6),
        closed_form=6, citation_key="west2001",
        graph_name="cycle C6", formula="n (even)"))
    fixtures.append(structured_maxcut_fixture(
        "gt_maxcut_cycle_c7", n=7, edges=cycle_graph_edges(7),
        closed_form=6, citation_key="west2001",
        graph_name="cycle C7", formula="n-1 (odd)"))
    # Complete bipartite K_{m,n}: max-cut = m*n (Diestel 2017).
    fixtures.append(structured_maxcut_fixture(
        "gt_maxcut_bipartite_k33", n=6, edges=complete_bipartite_edges(3, 3),
        closed_form=9, citation_key="diestel2017",
        graph_name="complete bipartite K_{3,3}", formula="m*n = 3*3"))
    fixtures.append(structured_maxcut_fixture(
        "gt_maxcut_bipartite_k24", n=6, edges=complete_bipartite_edges(2, 4),
        closed_form=8, citation_key="diestel2017",
        graph_name="complete bipartite K_{2,4}", formula="m*n = 2*4"))
    # Hypercube Q_3: max-cut = d*2^(d-1) (Harary 1969).
    fixtures.append(structured_maxcut_fixture(
        "gt_maxcut_hypercube_q3", n=8, edges=hypercube_edges(3),
        closed_form=12, citation_key="harary1969",
        graph_name="hypercube Q3", formula="d*2^(d-1) = 3*4"))
    # Petersen graph: max-cut = 12 (Barahona 1983).
    fixtures.append(structured_maxcut_fixture(
        "gt_maxcut_petersen", n=10, edges=petersen_edges(),
        closed_form=12, citation_key="barahona1983",
        graph_name="Petersen", formula="12"))

    document = {
        "schema_version": SCHEMA_VERSION,
        "energy_convention": ENERGY_CONVENTION,
        "description": (
            "Brute-force-verifiable ground-truth optimization instances. Every "
            "optimum, degeneracy, and witness is proven by exhaustive enumeration. "
            "Use to score a Gibbsiq solver against known-optimal answers."
        ),
        "generator": GENERATOR,
        "families": sorted({f["family"] for f in fixtures}),
        "fixtures": fixtures,
    }
    return document


def checksum(document: dict[str, Any]) -> str:
    payload = json.dumps(document, sort_keys=True, separators=(",", ":")).encode("utf-8")
    return hashlib.sha256(payload).hexdigest()


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--out",
        type=Path,
        default=Path("reference/06-benchmarks/fixtures/ground-truth-small.json"),
        help="Output path for the generated corpus.",
    )
    args = parser.parse_args(argv)

    document = build_corpus()
    document["content_sha256"] = checksum(
        {k: v for k, v in document.items() if k != "content_sha256"}
    )

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(json.dumps(document, indent=2) + "\n", encoding="utf-8")

    print(f"wrote {len(document['fixtures'])} fixtures to {args.out}")
    print(f"families: {', '.join(document['families'])}")
    print(f"content_sha256: {document['content_sha256']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
